In [1]:
import torch

### Initializing Tensor

In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"
my_tensor = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32,
                         device=device, requires_grad=True)
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)


In [3]:
# Attribute of Tensor
print(f"my_tensor = {my_tensor}")
print(f"Datatype of my_tensor = {my_tensor.dtype}")
print(f"my_tensor is in Device = {my_tensor.device}")
print(f"Shape of my_tensor = {my_tensor.shape}")
print(f"If my_tensor requires gradient = {my_tensor.requires_grad}")

my_tensor = tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)
Datatype of my_tensor = torch.float32
my_tensor is in Device = cpu
Shape of my_tensor = torch.Size([2, 3])
If my_tensor requires gradient = True


### Other common initialization methods

In [4]:
x = torch.empty(size=(3,3))
print(x)

tensor([[0.0000e+00, 0.0000e+00, 7.0295e+28],
        [6.1949e-04, 3.9177e-02, 4.7429e+30],
        [5.1476e+22, 7.9325e+34, 3.0304e+35]])


In [5]:
x = torch.zeros(3,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [6]:
x = torch.rand(3,3)
print(x)

tensor([[0.7470, 0.4038, 0.1641],
        [0.2524, 0.9051, 0.6315],
        [0.9602, 0.3261, 0.5279]])


In [7]:
x = torch.ones(3,3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [8]:
x = torch.eye(3,3)
print(x)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [9]:
x = torch.arange(start=0,end=5,step=1)
print(x)

tensor([0, 1, 2, 3, 4])


In [10]:
x = torch.linspace(start=0.1,end=1,steps=10)
print(x)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


In [11]:
x = torch.empty(size=(1,5)).normal_(mean=0,std=1)
print(x)

tensor([[-0.6955,  0.5520,  0.4266, -1.2111,  0.6014]])


In [12]:
x = torch.empty(size=(1,5)).uniform_(0,1)
print(x)

tensor([[0.6198, 0.8855, 0.5940, 0.0935, 0.9097]])


In [13]:
x = torch.diag(torch.ones(3))
print(x)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


### Initializing the tensor of different types and conversion to other types (int,float,double)

In [14]:
tensor = torch.arange(5)
print(tensor.bool())   # Boolean True/False
print(tensor.short())  # int16
print(tensor.long())   # int64
print(tensor.half())   # float16
print(tensor.float())  # float32
print(tensor.double()) #float64

tensor([False,  True,  True,  True,  True])
tensor([0, 1, 2, 3, 4], dtype=torch.int16)
tensor([0, 1, 2, 3, 4])
tensor([0., 1., 2., 3., 4.], dtype=torch.float16)
tensor([0., 1., 2., 3., 4.])
tensor([0., 1., 2., 3., 4.], dtype=torch.float64)


In [15]:
### Array to Tensor conversion and vice-versa
import numpy as np
np_array = np.zeros((5,5))
print(np_array)

tensor = torch.from_numpy(np_array)
print(tensor)

np_array_back = tensor.numpy()
print(np_array_back)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### Tensor Math & Comparison Operations

In [16]:
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])

In [17]:
# Addition
z1 = torch.empty(3)
torch.add(x,y,out=z1)

tensor([10., 10., 10.])

In [18]:
z2 = torch.add(x,y)
z2

tensor([10, 10, 10])

In [19]:
z = x+y
z

tensor([10, 10, 10])

In [20]:
# Subtraction
z = x - y
z

tensor([-8, -6, -4])

In [21]:
# Division
z = torch.true_divide(x,y)
z

tensor([0.1111, 0.2500, 0.4286])

In [22]:
# Inplace Operations: It will mutate the tensor in place or Doesn't create a copy
t = torch.zeros(3)
t.add_(x) # Any operation followed by '_' means operation is inplace
t

tensor([1., 2., 3.])

In [23]:
t+= x # Other way of doing in_place
t

tensor([2., 4., 6.])

In [24]:
# Exponentiation
z = x.pow(2)
z

tensor([1, 4, 9])

In [25]:
z = x**2
z

tensor([1, 4, 9])

In [26]:
# Simple Cpomparisons
z = x > 1
z

tensor([False,  True,  True])

In [27]:
#Matrix Multiplication
x1 = torch.rand(2,5)
x2 = torch.rand(5,3)
x3 = torch.mm(x1,x2) 
x3

tensor([[0.8173, 1.0610, 0.9112],
        [2.0784, 2.6749, 1.7914]])

In [28]:
x4 = x1.mm(x2) 
x4

tensor([[0.8173, 1.0610, 0.9112],
        [2.0784, 2.6749, 1.7914]])

In [29]:
# Matrix Exponentiation
matrix_exp = torch.rand(5,5)
matrix_exp.matrix_power(3)

tensor([[3.6037, 5.3993, 8.7463, 2.5052, 6.9560],
        [2.4156, 3.9421, 6.4850, 2.1005, 5.0628],
        [2.2621, 3.9664, 6.1014, 1.7799, 4.8295],
        [3.3911, 5.4191, 8.3503, 2.5959, 6.5505],
        [1.9874, 3.0254, 5.0044, 1.4092, 3.9677]])

In [30]:
# Element-wise Multiplication
z = x*y
z

tensor([ 9, 16, 21])

In [31]:
# Dot Product
z = torch.dot(x,y)
z

tensor(46)

In [32]:
# Batch Matrix multiplication
batch = 32
n = 10
m = 20
p = 30

tensor1 = torch.rand(batch,m,n)
tensor2 = torch.rand(batch,n,p)
out_bmm = torch.bmm(tensor1,tensor2) # batch,n,p

In [33]:
# Example of Broadcasting
x1 = torch.rand((5,5))
x2 = torch.rand((1,5))
z = x1 - x2
z

tensor([[ 0.7167, -0.0609, -0.1026, -0.1415,  0.2855],
        [ 0.5666, -0.3349, -0.7450,  0.3568, -0.0268],
        [ 0.9050,  0.0414, -0.7378, -0.0548, -0.6380],
        [ 0.5369, -0.2749, -0.2690,  0.1044, -0.4090],
        [ 0.3882, -0.2155, -0.2439,  0.1960, -0.4560]])

In [34]:
z = x1**x2
z

tensor([[0.9861, 0.8910, 0.8961, 0.5775, 0.9986],
        [0.9747, 0.6276, 0.2541, 0.8852, 0.7643],
        [0.9977, 0.9881, 0.2612, 0.6525, 0.1572],
        [0.9721, 0.6858, 0.7299, 0.7588, 0.4276],
        [0.9571, 0.7430, 0.7549, 0.8091, 0.3793]])

In [35]:
# Other usefule operations
sum_x = torch.sum(x,dim=0)
sum_x

tensor(6)

In [36]:
values,indices = torch.max(x,dim=0)
values,indices

(tensor(3), tensor(2))

In [37]:
values,indices = torch.min(x,dim=0)
values,indices

(tensor(1), tensor(0))

In [38]:
abs_x = torch.abs(x)
abs_x

tensor([1, 2, 3])

In [39]:
torch.argmax(x,dim=0) # x.max(dim=0)

tensor(2)

In [40]:
torch.argmin(x,dim=0)

tensor(0)

In [41]:
mean_x = torch.mean(x.float(),dim=0)
mean_x

tensor(2.)

In [42]:
torch.eq(x,y)

tensor([False, False, False])

In [43]:
sorted_y,indices = torch.sort(y,dim=0,descending=False)
sorted_y,indices

(tensor([7, 8, 9]), tensor([2, 1, 0]))

In [44]:
torch.clamp(x,min=0,max=10)

tensor([1, 2, 3])

In [45]:
x = torch.tensor([1,0,1,1,1],dtype=torch.bool)
z = torch.any(x)
z

tensor(True)

In [46]:
z = torch.all(x)
z

tensor(False)

### Tensor Indexing

In [47]:
batch_size = 10
features = 25
x = torch.rand((batch_size,features))

print(x[0].shape)
#or
print(x[0,:].shape)

torch.Size([25])
torch.Size([25])


In [48]:
print(x[:,0].shape)

torch.Size([10])


In [49]:
print(x[2,0:10])

tensor([0.1111, 0.1758, 0.9970, 0.0215, 0.6546, 0.2691, 0.0383, 0.3539, 0.7144,
        0.6778])


In [50]:
x[0,0]=100

In [51]:
## Fancy Indexing
x = torch.arange(10)
indices = [2,5,8]
print(x[indices])

tensor([2, 5, 8])


In [52]:
x = torch.rand((3,5))
rows = torch.tensor([1,0])
cols = torch.tensor([4,0])
print(x[rows,cols].shape)

torch.Size([2])


In [53]:
## More Advance Indexing
x = torch.arange(10)
print(x[(x<2)|(x>8)])
print(x[(x<2)&(x>8)])
print(x[(x.remainder(2)==0)])

tensor([0, 1, 9])
tensor([], dtype=torch.int64)
tensor([0, 2, 4, 6, 8])


In [54]:
# Useful Operations
print(torch.where(x>5 ,x , x*2)) #Terniary Operation
print(torch.tensor([0,0,1,2,2,3,4]).unique())
print(x.ndimension()) #if x (5x5x5)
print(x.numel()) #Count number of elements in x

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])
tensor([0, 1, 2, 3, 4])
1
10


### Tensor Reshaping

In [55]:
x = torch.arange(9)

In [56]:
x_3x3 = x.view(3,3)
x_3x3

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [57]:
x_3x3 = x.reshape(3,3) #Always work
x_3x3

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [58]:
y = x_3x3.t()
y

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])

In [59]:
x1 = torch.rand((2,5))
x2 = torch.rand((2,5))
print(torch.cat((x1,x2),dim=0).shape)
print(torch.cat((x1,x2),dim=1).shape)

torch.Size([4, 5])
torch.Size([2, 10])


In [60]:
# Flatten
z = x1.view(-1)
z.shape

torch.Size([10])

In [61]:
# Flatten
batch = 64
x = torch.rand((batch,2,5))
z = x.view(batch,-1)
z.shape

torch.Size([64, 10])

In [62]:
#Changing the dimensions
z = x.permute(0,2,1)
z.shape

torch.Size([64, 5, 2])

In [63]:
x = torch.arange(10)
x.unsqueeze(0).shape

torch.Size([1, 10])

In [64]:
x.unsqueeze(1).shape

torch.Size([10, 1])

In [65]:
x = torch.arange(10).unsqueeze(0).unsqueeze(1)
x.squeeze(1)
x.shape

torch.Size([1, 1, 10])